### ISSUE TITLE
73Linux doesn't install PAT

### ISSUE THREAD

**Issue by hwdornbush** [km4ack/73Linux#32]
I am trying to install 73Linux on an 8GB Pi running Pi OS 64-bit.
I selected PAT and PAT MENU.  PAT MENU installed but PAT did not install.
In the build log, I see 
dpkg: error processing archive /home/pi/.bap-source-files/pat_0.15.0_linux_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)

I have 
attached the "Installing pat" part of the build log.
[patbuild.txt](https://github.com/km4ack/73Linux/files/12215666/patbuild.txt)

**Comment by km4ack** [comment]
73Linux isn't recognizing the 64bit Pi OS correctly at the moment. As such, many things will not install. I am out of town this week but working on the code as time permits. This should be resolved soon. I already have the correction made but need to test before release. See issue #29. 32bit Pi OS is working correctly at this time. The issue only impacts 64bit version of Pi OS.

**Comment by km4ack** [comment]
Should be resolved in 4.0.1

**Comment by hwdornbush** [comment]
I installed 4.0.1 and PAT is still not installed.

pi@Pi4-8:~ $ pat configure
bash: pat: command not found

When I try to run Pat Menu, I get a popup:

invalid entry desktop file: 'usr/local/share/applications/patmenu2.desktop'
